### ISSUE TITLE
Discord Messages over 2000 Characters Fail

### ISSUE THREAD

**Issue by rlywtf** [rlywtf/DiscordianAI#14]
The discord client kicks out an error for lengthy responses to things like "write me a contract". These types of responses should provide a link with the full output, summarize the response in a shorter total length, or break the response up into multiple Discord messages.

Example: https://stackoverflow.com/questions/60686321/discord-js-content-must-be-2000-or-fewer-in-length

```2023-12-19 02:10:00,932 [ERROR] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/root/DiscordianAI/bot.py", line 312, in on_message
    await message.channel.send(response)
  File "/usr/local/lib/python3.10/dist-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.```

**Comment by rlywtf** [comment]
![image](https://github.com/rlywtf/DiscordianAI/assets/53841159/8b3e9d68-9006-4758-9a89-96bde73bbf13)

**Comment by rlywtf** [comment]
![image](https://github.com/rlywtf/DiscordianAI/assets/53841159/fd54922a-fb9e-40b8-8936-4dd4fc4a436d)

**Comment by rlywtf** [comment]
![image](https://github.com/rlywtf/DiscordianAI/assets/53841159/70950b49-a23a-4679-94f7-8c0643a06444)
